"""Orchestrator: ingest threat intel -> draft KQL -> validate -> write proposals.

Writes validated, auto-proposed detections to a dated file under the configured
output_dir. Never touches the hand-curated tactic files. Emits `has_changes` to
$GITHUB_OUTPUT so the workflow only opens a PR when something was produced.
"""
from __future__ import annotations

import datetime as dt
import os
import pathlib

import yaml

import generate
import ingest
import validate as validator

ROOT = pathlib.Path(__file__).resolve().parents[1]
HERE = pathlib.Path(__file__).parent


def _render(detections: list[dict], threats: list[dict], date: str) -> str:
    threat_ids = ", ".join(sorted({t["id"] for t in threats}))
    out = [
        f"# Auto-proposed KQL detections — {date}",
        "",
        "> ⚠️ **Machine-drafted, unreviewed.** These detections were generated from "
        "recent threat intelligence and passed only *static* KQL validation "
        "(syntax + known Advanced Hunting schema). They have **not** been run "
        "against a live tenant. Review, tune, and test before promoting any of "
        "them into the curated tactic files.",
        "",
        f"**Source intel:** {threat_ids}",
        "",
        "---",
        "",
    ]
    for i, d in enumerate(detections, 1):
        out += [
            f"## {i}) {d['title']}",
            "",
            f"**Tactic:** {d['tactic']}  ",
            f"**ATT&CK:** {d['technique']}  ",
            f"**Severity:** {d['severity']}  ",
            f"**Purpose:** {d['purpose']}",
            "",
            "```kusto",
            d["kql"].strip(),
            "```",
            "",
            f"**Tuning notes:** {d['tuning_notes']}",
            "",
            "---",
            "",
        ]
    return "\n".join(out)


def _set_output(key: str, value: str) -> None:
    gh_out = os.environ.get("GITHUB_OUTPUT")
    if gh_out:
        with open(gh_out, "a", encoding="utf-8") as fh:
            fh.write(f"{key}={value}\n")


def main() -> int:
    config = yaml.safe_load((HERE / "config.yaml").read_text())

    threats = ingest.gather(config)
    print(f"[run] Gathered {len(threats)} threat(s) from intel feeds.")
    if not threats:
        _set_output("has_changes", "false")
        return 0

    drafted = generate.generate(threats, config)
    print(f"[run] Model drafted {len(drafted)} candidate detection(s).")

    validated: list[dict] = []
    for d in drafted:
        result = validator.validate(d.get("kql", ""), d.get("tactic"))
        status = "PASS" if result.ok else "FAIL"
        print(f"[run] validate [{status}] {d.get('title','?')}")
        if not result.ok:
            print(str(result))
        else:
            validated.append(d)

    if not validated:
        print("[run] No detections passed validation - nothing to propose.")
        _set_output("has_changes", "false")
        return 0

    date = dt.date.today().isoformat()
    out_dir = ROOT / config.get("output_dir", "AutoGenerated")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{date}_proposed.md"
    out_file.write_text(_render(validated, threats, date), encoding="utf-8")

    print(f"[run] Wrote {len(validated)} detection(s) to {out_file.relative_to(ROOT)}")
    _set_output("has_changes", "true")
    _set_output("count", str(len(validated)))
    _set_output("date", date)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
